config/routes.rb
Etsydemo::Application.routes.draw do
  devise_for :users
  resources :artists

  get "pages/about"
  get "pages/contact"

  root 'artists#index'
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @artist }
      else
        format.html { render action: 'new' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :description, :price, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist, :html => { :multipart => true }) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>


<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist, class: "btn btn-link" %> 
<%= link_to 'Back', artists_path, class: "btn btn-link" %>

app/views/artists/index.html.erb
<div class="center">
  <div class="row">
    <% @artists.each do |artist| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <%= image_tag artist.image.url %>
          <div class="caption">
            <%= link_to artist do %>
              <h1><%= artist.name %></h1>
            <% end %>
            <p>Lorem ipsum dolor sit amet.</p>
            <p><%= artist.price %>  SEK</p>
            <%= link_to 'Show', artist, class: "btn btn-link" %>
            <%= link_to 'Edit', edit_artist_path(artist), class: "btn btn-link" %>
            <%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<br>

<%= link_to 'New Artist', new_artist_path, class: "btn btn-link" %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path, class: "btn btn-link" %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
			<%= image_tag @artist.image.url %><br>
			<div class="container" style="width:80%">
				<p><%= @artist.description %><p>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<h1><%= @artist.name %></h1>
		<p><%=  @artist.price %></p>
	</div>
</div>


<%= link_to 'Edit', edit_artist_path(@artist), class: "btn btn-link" %> |
<%= link_to 'Back', artists_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<p>Copyright 2014 </p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Indiebook</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Etsydemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">

	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<%= yield %>
	<%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>